In [1]:
import pandas as pd
import nltk


from nltk import word_tokenize,sent_tokenize

trainfile = "C:/Users/bahubali/Documents/stanford140/train.csv"
train = pd.read_csv(trainfile,header = None,encoding = 'iso-8859-1')

testfile = "C:/Users/bahubali/Documents/stanford140/test.csv"
test = pd.read_csv(testfile,header = None,encoding = 'iso-8859-1')


In [2]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
0    1600000 non-null int64
1    1600000 non-null int64
2    1600000 non-null object
3    1600000 non-null object
4    1600000 non-null object
5    1600000 non-null object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB


In [3]:
train.head()

0           1                             2         3                4  \
0  0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  _TheSpecialOne_   
1  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY    scotthamilton   
2  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY         mattycus   
3  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          ElleCTF   
4  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY           Karoli   

                                                   5  
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1  is upset that he can't update his Facebook by ...  
2  @Kenichan I dived many times for the ball. Man...  
3    my whole body feels itchy and like its on fire   
4  @nationwideclass no, it's not behaving at all....

In [4]:
train.describe()

0             1
count  1.600000e+06  1.600000e+06
mean   2.000000e+00  1.998818e+09
std    2.000001e+00  1.935761e+08
min    0.000000e+00  1.467810e+09
25%    0.000000e+00  1.956916e+09
50%    2.000000e+00  2.002102e+09
75%    4.000000e+00  2.177059e+09
max    4.000000e+00  2.329206e+09

In [5]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 6 columns):
0    498 non-null int64
1    498 non-null int64
2    498 non-null object
3    498 non-null object
4    498 non-null object
5    498 non-null object
dtypes: int64(2), object(4)
memory usage: 23.4+ KB


In [6]:
import re #import regular expressions
from bs4 import BeautifulSoup # Import BeautifulSoup into your workspace
from nltk.corpus import stopwords # Import the stop word list



In [7]:
def tweet_to_words(raw_tweet):
    # Function to convert a raw tweet to a string of words
    # The input is a single string (a raw tweet), and 
    # the output is a single string (a preprocessed tweet)
    #
    # 1. Remove HTML
    tweet_text = BeautifulSoup(raw_tweet,"lxml").get_text() 
    #
    # 2. Remove non-letters        
    letters_only = re.sub("[^a-zA-Z]", " ", tweet_text) 
    #
    # 3. Convert to lower case, split into individual words
    words = letters_only.lower().split()                             
    #
    # 4. In Python, searching a set is much faster than searching
    #   a list, so convert the stop words to a set
    stops = set(stopwords.words("english"))                  
    # 
    # 5. Remove stop words
    meaningful_words = [w for w in words if not w in stops]   
    #
    # 6. Join the words back into one string separated by space, 
    # and return the result.
    return( " ".join( meaningful_words )) 

bagofwords = [tweet_to_words(tweet) for tweet in train[5]]

C:\Users\bahubali\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning: "b' i just received my G8 viola exam.. and its... well... .. disappointing.. :\\..'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)
C:\Users\bahubali\Anaconda3\lib\site-packages\bs4\__init__.py:219: UserWarning: "b'E3 ON PLAYSTATION HOME IN ABOUT AN HOUR!!!!!!!!!! \\../  \\../'" looks like a filename, not markup. You shouldprobably open this file and pass the filehandle intoBeautiful Soup.
  'Beautiful Soup.' % markup)


In [8]:
print(bagofwords[0])

switchfoot http twitpic com zl awww bummer shoulda got david carr third day


In [9]:
len(bagofwords)

1600000

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 200) 

train_data_features = vectorizer.fit_transform(bagofwords)


In [11]:
train_data_features = train_data_features.toarray()
print(train_data_features.shape)

(1600000, 200)


In [12]:
# Take a look at the words in the vocabulary
vocab = vectorizer.get_feature_names()
print(vocab)

['actually', 'already', 'also', 'always', 'amazing', 'another', 'away', 'awesome', 'baby', 'back', 'bad', 'bed', 'best', 'better', 'big', 'birthday', 'bit', 'bored', 'cant', 'com', 'come', 'coming', 'cool', 'could', 'damn', 'day', 'days', 'done', 'dont', 'early', 'even', 'ever', 'everyone', 'excited', 'feel', 'feeling', 'finally', 'find', 'first', 'follow', 'friend', 'friends', 'fun', 'game', 'get', 'getting', 'girl', 'glad', 'go', 'god', 'going', 'gonna', 'good', 'got', 'gotta', 'great', 'guess', 'guys', 'haha', 'happy', 'hard', 'hate', 'hear', 'help', 'hey', 'hi', 'home', 'hope', 'hot', 'hours', 'house', 'http', 'im', 'keep', 'know', 'last', 'late', 'later', 'left', 'let', 'life', 'like', 'little', 'live', 'lol', 'long', 'look', 'looking', 'looks', 'lost', 'lot', 'love', 'ly', 'made', 'make', 'makes', 'man', 'maybe', 'might', 'miss', 'missed', 'mom', 'morning', 'movie', 'much', 'music', 'need', 'never', 'new', 'next', 'nice', 'night', 'nothing', 'oh', 'ok', 'old', 'omg', 'one', 'part

In [13]:
import numpy as np

# Sum up the counts of each vocabulary word
dist = np.sum(train_data_features, axis=0)

# For each, print the vocabulary word and the number of times it 
# appears in the training set
for tag, count in zip(vocab, dist):
    print(count, tag)

9997 actually
14779 already
10442 also
14947 always
11851 amazing
14577 another
12299 away
18331 awesome
10564 baby
56986 back
27403 bad
22263 bed
16495 best
23250 better
11312 big
10406 birthday
24433 bit
10647 bored
17684 cant
52760 com
25135 come
10396 coming
14547 cool
21925 could
11733 damn
89857 day
19550 days
15338 done
18238 dont
11826 early
19201 even
13155 ever
16405 everyone
9818 excited
30274 feel
15155 feeling
11945 finally
14196 find
16813 first
11717 follow
11385 friend
14604 friends
28716 fun
9709 game
82202 get
24368 getting
11121 girl
10535 glad
74135 go
9558 god
64635 going
23831 gonna
91389 good
61466 got
9298 gotta
33539 great
11510 guess
14085 guys
31518 haha
27084 happy
9729 hard
19833 hate
10049 hear
11835 help
19145 hey
9532 hi
40557 home
33922 hope
11120 hot
13384 hours
13085 house
71582 http
52377 im
11299 keep
52066 know
35765 last
9245 late
10211 later
11497 left
15056 let
16681 life
78595 like
17047 little
10591 live
59286 lol
17168 long
13393 look
13543 l

In [14]:
print("Training the random forest...")
from sklearn.ensemble import RandomForestClassifier

# Initialize a Random Forest classifier with 100 trees
forest = RandomForestClassifier(n_estimators = 50) 

# Fit the forest to the training set, using the bag of words as 
# features and the sentiment labels as the response variable
#
# This may take a few minutes to run
forest = forest.fit( train_data_features, train[0] )

Training the random forest...


In [15]:
test_bagofwords = [tweet_to_words(tweet) for tweet in test[5]]
print(len(test_bagofwords))
print(test_bagofwords[0])

498
stellargirl loooooooovvvvvveee kindle dx cool fantastic right


In [16]:
# Get a bag of words for the test set, and convert to a numpy array
test_data_features = vectorizer.transform(test_bagofwords)
test_data_features = test_data_features.toarray()

In [17]:
# Use the random forest to make sentiment label predictions
result = forest.predict(test_data_features)

print(len(result))
print(result)

498
[4 4 4 4 0 4 0 4 4 4 0 0 0 4 4 4 0 4 0 4 0 4 0 4 0 4 4 0 4 4 4 4 0 0 0 0 4
 0 0 0 0 4 0 0 4 4 4 0 4 0 0 4 4 4 4 4 4 4 4 0 0 4 4 4 4 4 4 4 4 4 4 4 0 0
 4 4 4 4 0 0 4 0 4 4 4 0 0 0 4 4 4 4 0 0 0 0 0 0 0 0 4 4 4 4 4 0 0 4 4 4 4
 4 4 4 4 0 0 4 4 4 0 4 4 0 4 4 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4 0 0 0 0 0 4 0
 0 0 4 4 0 4 4 4 4 0 4 4 4 4 0 4 0 4 4 0 4 4 0 4 4 4 4 4 0 4 4 4 0 4 4 4 0
 4 4 4 4 4 4 0 0 4 0 4 4 4 4 4 4 4 4 0 4 0 0 4 4 4 0 0 4 0 0 0 0 0 0 4 0 4
 4 4 0 0 4 0 0 4 0 4 4 4 4 0 4 4 4 4 4 0 4 4 4 4 4 4 4 4 0 4 4 4 4 4 4 4 4
 4 4 4 4 0 4 4 4 4 4 4 4 0 0 0 4 4 0 4 4 4 0 4 0 4 4 4 0 4 4 4 4 4 0 0 4 0
 0 0 4 4 4 4 4 4 4 4 0 0 4 4 4 4 0 4 0 4 0 4 4 4 0 4 4 4 4 4 4 4 4 4 4 4 0
 0 0 4 0 4 4 4 0 4 4 4 0 4 4 4 4 4 4 4 4 4 0 4 4 4 4 4 4 4 4 4 0 4 4 4 4 4
 4 4 4 0 4 4 0 0 0 0 4 0 4 0 4 4 4 4 4 0 0 0 4 4 0 0 0 4 4 4 0 4 0 4 4 0 0
 4 0 0 4 4 4 4 4 4 4 0 4 4 0 4 0 4 4 4 4 0 0 0 4 4 4 4 4 4 4 4 4 4 0 4 4 0
 4 4 4 4 4 4 4 4 4 0 4 0 4 4 0 4 4 4 4 0 0 4 0 4 0 4 0 4 4 4 0 4 4 4 4 0 4
 0 0 4 4 4 4 4 4 4 4 

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
print(accuracy_score(test[0],result))
print(confusion_matrix(test[0],result))

0.491967871486
[[103   0  74]
 [ 17   0 122]
 [ 40   0 142]]
